version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:18.2.0
    steps:
      - checkout
      - run: mkdir test-reports
      - run:
          name: Download Selenium
          command: curl -O http://selenium-release.storage.googleapis.com/3.9/selenium-server-standalone-3.9.0.jar
      - run:
          name: Start Selenium
          command: java -jar selenium-server-standalone-3.9.0.jar -log test-reports/selenium.log
          background: true
      - run:
          name: Start install Selenium
          command: sudo apt-get install libnspr4 libnss3 libnss3-nssdb libnss3-tools
      - run:
          name: Startssssss Selenium
          command: sudo apt-get install libnss3-dev libgdk-pixbuf2.0-dev libgtk-3-dev libxss-dev
      - run:
          name: Start ddddSelenium
          command: sudo apt-file search  libnss3.so
  test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: build
          command: mvn -B -DskipTests clean package

      - run:
          name: test
          command: mvn test
      - store_test_results:
          path: target/surefire-reports
workflows:
  sample:
    jobs:
      - build
      - test:
         requires:
               - build