version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:18.2.0
    steps:
      - run:
          name: Start install Selenium
          command: sudo apt remove libnss3
      - run:
          name: Start install11 Selenium
          command: sudo apt autoclean && sudo apt autoremove
      - run:
          name: Start install111 Selenium
          command: ssudo apt update
      - run:
          name: Start install1111 Selenium
          command: sudo apt install libnss3

workflows:
  sample:
    jobs:
      - build