version: 2.1
jobs:
  build: # name of your job
    machine: # executor type
      image: ubuntu-2004:202010-01  
    test:
 
     - image: ubuntu-2004:202010-01 
    steps:
      - checkout
      - run:
          name: build
          command: mvn -B -DskipTests clean package
      # Then run your tests!
      - run:
          name: test
          command: mvn test
      - store_test_results:
          path: target/surefire-reports
workflows:
  sample:
    jobs:
      - build
      - test