version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:18.2.0
    steps:
      - checkout
      - run: mkdir test-reports
      - run:
          name: Download Selenium
          command: curl -O http://selenium-release.storage.googleapis.com/3.9/selenium-server-standalone-3.9.0.jar
      - run:
          name: Start install Selenium
          command: sudo apt update
      - run:
          name: Startssssss Selenium
          command: apt-get update \
                   && apt-get install -y \
                   unzip \
                   wget \
                   libnss3 \
                   && rm -rf /var/lib/apt/lists/* \
                   && echo "progress = dot:giga" | tee /etc/wgetrc \
                   && mkdir -p /mnt /opt /data \
                   && wget https://github.com/andmarios/duphard/releases/download/v1.0/duphard -O /bin/duphard \
                   && chmod +x /bin/duphard
  test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: build
          command: mvn -B -DskipTests clean package

      - run:
          name: test
          command: mvn test
      - store_test_results:
          path: target/surefire-reports
workflows:
  sample:
    jobs:
      - build
      - test:
         requires:
               - build