version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:16.13.1-browsers
    steps:
      - checkout
      - run: mkdir test-reports
      - run:
          name: Download Selenium
          command: curl -O http://selenium-release.storage.googleapis.com/3.9/selenium-server-standalone-3.9.0.jar
      - run:
          name: Start Selenium
          command: java -jar selenium-server-standalone-3.9.0.jar -log test-reports/selenium.log
          background: true    
  test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: build
          command: mvn -B -DskipTests clean package install
      # Then run your tests!
      - run:
          name: test
          command: mvn test
      - store_test_results:
          path: target/surefire-reports
workflows:
  sample:
    jobs:
      - build
      - test