version: 2.1
jobs:
  test:
    docker:
      - image: cimg/node:18.2.0
    steps:
      - checkout
      - run:
          name: build
          command: mvn -B -DskipTests clean package

      - run:
          name: test
          command: mvn test
      - store_test_results:
          path: target/surefire-reports
workflows:
  sample:
    jobs:
      - build
      - test