version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:18.2.0-browsers
    steps:
      - checkout
      - run: mkdir test-reports
      - run:
          name: Download Selenium
          command: curl -O http://selenium-release.storage.googleapis.com/3.9/selenium-server-standalone-3.9.0.jar
      - run:
          name: Start Selenium
          command: java -jar selenium-server-standalone-3.9.0.jar -log test-reports/selenium.log
          background: true
      - run:
          name: Install latest version of ChromeDriver Sample
          command: |
            sudo wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            sudo sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
            sudo apt-get update
            sudo apt-get install google-chrome-stable
      - run:
          name: Install latest version of ChromeDriver Sample
          command: |
            sudo wget https://chromedriver.storage.googleapis.com/101.0.4951.41/chromedriver_linux64.zip
            sudo unzip chromedriver_linux64.zip
            sudo rm chromedriver_linux64.zip
            sudo mv chromedriver /usr/bin/
            sudo chmod 777 /usr/bin/chromedriver
            sudo apt-get install libxi6 libgconf-2-4
            sudo apt-get -y install xvfb gtk2-engines-pixbuf
            sudo apt-get -y install xfonts-cyrillic xfonts-100dpi xfonts-75dpi xfonts-base xfonts-scalable
            sudo apt-get install xvfb
            sudo apt-get -y install imagemagick x11-apps
      - run:
          name: Running X virtual framebuffer
          command: Xvfb :0 -ac &    
  test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: build
          command: mvn -B -DskipTests clean package

      - run:
          name: test
          command: mvn test
      - store_test_results:
          path: target/surefire-reports
workflows:
  sample:
    jobs:
      - build
      - test:
         requires:
               - build