version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/circleCiTesting

    environment:
      MAVEN_OPTS: -Xmx3200m
    
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          - v1-dependencies-

      - run: mvn dependency:go-offline

      - run:
          name: Install latest version of ChromeDriver Sample
          command: |
            sudo wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            sudo sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
            sudo apt-get update
            sudo apt-get install google-chrome-stable
      - run:
          name: Install latest version of ChromeDriver Sample
          command: |
            sudo wget https://chromedriver.storage.googleapis.com/101.0.4951.41/chromedriver_linux64.zip
            sudo unzip chromedriver_linux64.zip
            sudo rm chromedriver_linux64.zip
            sudo mv chromedriver /usr/bin/
            sudo chmod 777 /usr/bin/chromedriver
            sudo apt-get install libxi6 libgconf-2-4
            sudo apt-get -y install xvfb gtk2-engines-pixbuf
            sudo apt-get -y install xfonts-cyrillic xfonts-100dpi xfonts-75dpi xfonts-base xfonts-scalable
            sudo apt-get install xvfb
            sudo apt-get -y install imagemagick x11-apps
      - run:
          name: Running X virtual framebuffer
          command: Xvfb :0 -ac &

      - run:
          name: Run Tests
          command: |
            export DISPLAY=:99
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - run:
          name: test
          command: mvn test
workflows:
  sample:
    jobs:
      - build
      - test:
         requires:
               - build