version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:12.16
    steps:
      - checkout
      - run: mkdir test-reports
      - run:
          name: Download Selenium
          command: curl -O http://selenium-release.storage.googleapis.com/3.9/selenium-server-standalone-3.9.0.jar
      - run:
          name: Start Selenium
          command: java -jar selenium-server-standalone-3.9.0.jar -log test-reports/selenium.log
          background: true
      - run:
          name: Start install Selenium
          command: sudo apt install libgconf-2-4 libatk1.0-0 libatk-bridge2.0-0 libgdk-pixbuf2.0-0 libgtk-3-0 libgbm-dev libnss3-dev libxss-dev
  test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: build
          command: mvn -B -DskipTests clean package

      - run:
          name: test
          command: mvn test
      - store_test_results:
          path: target/surefire-reports
workflows:
  sample:
    jobs:
      - build
      - test:
         requires:
               - build